version: 2
jobs:
  build:
    working_directory: /workdir
    docker:
      - image: docker:17.06.0-ce-git
        environment:
          RELEASE_SERIES_LIST: "10,11,9.6"
          LATEST_STABLE: "11"
          DISTRIBUTIONS_LIST: "centos-7,debian-9,ol-7"
          IMAGE_NAME: postgresql
          DOCKER_PROJECT: bitnami
          QUAY_PROJECT: bitnami
          GCLOUD_PROJECT: bitnami-containers
          AZURE_PROJECT: bitnami

    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Upgrade system packages (workaround - https://github.com/docker-library/docker/issues/72)
          command: |
            apk upgrade --no-cache
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl bash coreutils
      - run:
          name: Docker info
          command: |
            docker version
            docker info
      - deploy:
          name: Publish docker image
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              curl -sL https://raw.githubusercontent.com/bitnami/test-infra/master/circle/docker-release-image.sh | bash -
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*(?<!-rhel-7)-r[0-9]+$/
